//SIGN IN SCREEN
export const UPDATE_SIGNIN_USERNAME_FIELD = 'UPDATE_SIGNIN_USERNAME_FIELD';
export const UPDATE_SIGNIN_PASSWORD_FIELD = 'UPDATE_SIGNIN_PASSWORD_FIELD';

//SIGN UP SCREEN
export const UPDATE_SIGNUP_USERNAME_FIELD = 'UPDATE_SIGNUP_USERNAME_FIELD';
export const UPDATE_SIGNUP_EMAIL_FIELD = 'UPDATE_SIGNUP_EMAIL_FIELD';
export const UPDATE_SIGNUP_PASSWORD_FIELD = 'UPDATE_SIGNUP_PASSWORD_FIELD';